'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { stores } from '@/data/stores';
import { products } from '@/data/products';
import { ADDITIONAL_REGION_STORES,FORT_WORTH_REGION_IDS,DALLAS_REGION_IDS,AUSTIN_REGION_IDS,SAN_ANTONIO_REGION_IDS,WEST_TEXAS_REGION_IDS,EAST_TEXAS_REGION_IDS,SOUTH_TEXAS_REGION_IDS,EAST_HOUSTON_REGION_IDS,WEST_HOUSTON_REGION_IDS } from '@/data/regions';
import { isUnavailableInventory, readInventorySnapshots, writeInventorySnapshots, type StoreInventorySnapshot } from '@/lib/inventoryTracking';

const allStores=[...stores,...ADDITIONAL_REGION_STORES];
const REGION_SETS:Record<string,Set<string>>={FORT_WORTH:FORT_WORTH_REGION_IDS,DALLAS:DALLAS_REGION_IDS,AUSTIN:AUSTIN_REGION_IDS,SAN_ANTONIO:SAN_ANTONIO_REGION_IDS,WEST_TEXAS:WEST_TEXAS_REGION_IDS,EAST_TEXAS:EAST_TEXAS_REGION_IDS,SOUTH_TEXAS:SOUTH_TEXAS_REGION_IDS,EAST_HOUSTON:EAST_HOUSTON_REGION_IDS,WEST_HOUSTON:WEST_HOUSTON_REGION_IDS};
const REGION_LABELS:Record<string,string>={FORT_WORTH:'Fort Worth',DALLAS:'Dallas',AUSTIN:'Austin',SAN_ANTONIO:'San Antonio',WEST_TEXAS:'West Texas',EAST_TEXAS:'East Texas',SOUTH_TEXAS:'South Texas',EAST_HOUSTON:'East Houston',WEST_HOUSTON:'West Houston'};
function regionName(storeId:string){for(const [key,set] of Object.entries(REGION_SETS))if(set.has(storeId))return REGION_LABELS[key];return 'Other / Unassigned'}

export default function UnavailablePage(){
 const [snapshots,setSnapshots]=useState<StoreInventorySnapshot[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState('');
 useEffect(()=>setSnapshots(readInventorySnapshots()),[]);
 const rows=useMemo(()=>snapshots.flatMap(snapshot=>snapshot.rows.filter(row=>isUnavailableInventory(row)).map(row=>{const store=allStores.find(s=>s.id===snapshot.storeId),product=products.find(p=>p.tcin===row.tcin);return{storeId:snapshot.storeId,storeName:store?.name??`Target #${snapshot.storeId}`,city:store?`${store.city}, ${store.state}`:'',region:regionName(snapshot.storeId),delivery:store?.deliveryDays?.join(' / ')??'—',tcin:row.tcin,brand:product?.brand??'',product:product?.name??row.tcin,category:product?.category??'',availability:row.availability,lastChecked:snapshot.refreshedAt}})).sort((a,b)=>a.region.localeCompare(b.region)||a.storeName.localeCompare(b.storeName)||a.product.localeCompare(b.product)),[snapshots]);
 const storeCount=new Set(rows.map(r=>r.storeId)).size,regionCount=new Set(rows.map(r=>r.region)).size;
 async function recheckUnavailable(){if(busy||rows.length===0)return;setBusy(true);const next=readInventorySnapshots();let recovered=0;try{for(let i=0;i<rows.length;i++){const item=rows[i];setProgress(`${i+1} / ${rows.length} — ${item.storeName} — ${item.product}`);try{const q=new URLSearchParams({tcin:item.tcin,storeId:item.storeId}),res=await fetch(`/api/inventory?${q.toString()}`),data=await res.json(),snapshot=next.find(s=>s.storeId===item.storeId),row=snapshot?.rows.find(r=>r.tcin===item.tcin);if(row){row.quantity=data.quantity??null;row.status=data.status??'UNKNOWN';row.availability=data.availability??'UNKNOWN';if(!isUnavailableInventory(row)&&row.quantity!==null)recovered++;if(snapshot)snapshot.refreshedAt=new Date().toISOString()}}catch{} }writeInventorySnapshots(next);setSnapshots(readInventorySnapshots());setProgress(`Complete — ${recovered} item${recovered===1?'':'s'} recovered to store inventory`)}finally{setBusy(false)}}
 return <main id="top"><header><div><div className="eyebrow">UNAVAILABLE HOLDING FILE</div><h1>Unavailable Watch</h1><p>These items are excluded from OOS and in-stock until Target returns a usable store quantity.</p></div><div className="headerActions"><Link className="navButton" href="/">Store Dashboard</Link><Link className="navButton" href="/regions">Regional Dashboard</Link><Link className="navButton" href="/orders">Case Additions Dashboard</Link><button className="primary" onClick={recheckUnavailable} disabled={busy||rows.length===0}>{busy?'Rechecking…':'Recheck Unavailable Now'}</button></div></header>
 {progress&&<section className="storeCard"><div><strong>Watch Status</strong><span>{progress}</span></div></section>}
 <section className="stats orderStats"><div className="stat neutral"><strong>{rows.length}</strong><span>Unavailable Items</span><small>Excluded from in-stock</small></div><div className="stat neutral"><strong>{storeCount}</strong><span>Stores Impacted</span><small>Current browser snapshot</small></div><div className="stat neutral"><strong>{regionCount}</strong><span>Regions Impacted</span><small>Current browser snapshot</small></div></section>
 <section className="analysisSection"><div className="sectionTitle"><div><h2>Current Watch List</h2><p>When a recheck returns a real quantity, the item automatically leaves this list and returns to its store.</p></div></div><div className="tableWrap"><table><thead><tr><th>Region</th><th>Store</th><th>Delivery</th><th>Brand</th><th>Item</th><th>Category</th><th>TCIN</th><th>Target Result</th><th>Last Checked</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={9}>No unavailable items are currently being held.</td></tr>:rows.map(r=><tr key={`${r.storeId}-${r.tcin}`}><td>{r.region}</td><td><strong>{r.storeName}</strong><br/><small>{r.city}</small></td><td>{r.delivery}</td><td>{r.brand}</td><td>{r.product}</td><td>{r.category}</td><td className="mono">{r.tcin}</td><td><span className="pill unknown">{r.availability}</span></td><td>{new Date(r.lastChecked).toLocaleString()}</td></tr>)}</tbody></table></div></section>
 <nav className="mobileBottomNav"><Link href="/">Store</Link><Link href="/regions">Regions</Link><a href="#top" className="active"><span>+</span>Watch</a><Link href="/orders">Orders</Link><button onClick={recheckUnavailable} disabled={busy||rows.length===0}>Recheck</button></nav>
 <footer>Unavailable Watch is currently stored in this browser with the inventory snapshots. A scheduled Monday recheck requires moving this watch list to persistent server-side storage.</footer></main>
}
