'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { stores } from '@/data/stores';
import { products } from '@/data/products';
import { ADDITIONAL_REGION_STORES,FORT_WORTH_REGION_IDS,DALLAS_REGION_IDS,AUSTIN_REGION_IDS,SAN_ANTONIO_REGION_IDS,WEST_TEXAS_REGION_IDS,EAST_TEXAS_REGION_IDS,SOUTH_TEXAS_REGION_IDS,EAST_HOUSTON_REGION_IDS,WEST_HOUSTON_REGION_IDS } from '@/data/regions';
import { getWeekStart, readOrderAdditions, type OrderAddition } from '@/lib/orderTracking';
import { isUnavailableInventory, readInventorySnapshots, saveStoreInventorySnapshot, type StoreInventorySnapshot } from '@/lib/inventoryTracking';

const allStores=[...stores,...ADDITIONAL_REGION_STORES];
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const REGION_SETS:Record<string,Set<string>>={DALLAS:DALLAS_REGION_IDS,FORT_WORTH:FORT_WORTH_REGION_IDS,AUSTIN:AUSTIN_REGION_IDS,SAN_ANTONIO:SAN_ANTONIO_REGION_IDS,WEST_TEXAS:WEST_TEXAS_REGION_IDS,EAST_TEXAS:EAST_TEXAS_REGION_IDS,SOUTH_TEXAS:SOUTH_TEXAS_REGION_IDS,EAST_HOUSTON:EAST_HOUSTON_REGION_IDS,WEST_HOUSTON:WEST_HOUSTON_REGION_IDS};
const REGION_LABELS:Record<string,string>={DALLAS:'Dallas',FORT_WORTH:'Fort Worth',AUSTIN:'Austin',SAN_ANTONIO:'San Antonio',WEST_TEXAS:'West Texas',EAST_TEXAS:'East Texas',SOUTH_TEXAS:'South Texas',EAST_HOUSTON:'East Houston',WEST_HOUSTON:'West Houston'};
type RegionSummary={key:string;label:string;stores:number;refreshed:number;healthy:number;low:number;oos:number;unavailable:number;known:number;rate:number|null;casesAdded:number;dollarsAdded:number;lastRefreshed?:string};
function rateClass(rate:number|null){if(rate===null)return'unknown';if(rate>=98.5)return'healthy';if(rate>=95)return'low';return'oos'}

export default function RegionalDashboard(){
 const [snapshots,setSnapshots]=useState<StoreInventorySnapshot[]>([]),[orders,setOrders]=useState<OrderAddition[]>([]),[refreshingKey,setRefreshingKey]=useState<string|null>(null),[refreshAll,setRefreshAll]=useState(false),[refreshProgress,setRefreshProgress]=useState('');
 useEffect(()=>{setSnapshots(readInventorySnapshots());setOrders(readOrderAdditions())},[]);
 const snapshotMap=useMemo(()=>new Map(snapshots.map(s=>[s.storeId,s])),[snapshots]),currentWeek=getWeekStart(),currentWeekOrders=useMemo(()=>orders.filter(r=>r.weekStart===currentWeek),[orders,currentWeek]);
 const summaries=useMemo<RegionSummary[]>(()=>Object.entries(REGION_SETS).map(([key,ids])=>{const regionStores=allStores.filter(s=>ids.has(s.id)),regionSnapshots=regionStores.map(s=>snapshotMap.get(s.id)).filter(Boolean) as StoreInventorySnapshot[],allRows=regionSnapshots.flatMap(s=>s.rows),unavailable=allRows.filter(r=>isUnavailableInventory(r)).length,rows=allRows.filter(r=>!isUnavailableInventory(r)),healthy=rows.filter(r=>r.status==='HEALTHY').length,low=rows.filter(r=>r.status==='LOW').length,oos=rows.filter(r=>r.status==='OOS').length,known=healthy+low+oos,regionOrders=currentWeekOrders.filter(r=>ids.has(r.storeId)),lastRefreshed=regionSnapshots.length?regionSnapshots.map(s=>s.refreshedAt).sort().at(-1):undefined;return{key,label:REGION_LABELS[key],stores:regionStores.length,refreshed:regionSnapshots.length,healthy,low,oos,unavailable,known,rate:known>0?(healthy/known)*100:null,casesAdded:regionOrders.reduce((sum,r)=>sum+r.cases,0),dollarsAdded:regionOrders.reduce((sum,r)=>sum+(r.addedValue??0),0),lastRefreshed}}).sort((a,b)=>{if(a.rate===null&&b.rate!==null)return 1;if(a.rate!==null&&b.rate===null)return-1;if(a.rate!==null&&b.rate!==null&&a.rate!==b.rate)return a.rate-b.rate;return a.label.localeCompare(b.label)}),[snapshotMap,currentWeekOrders]);
 const totalStores=summaries.reduce((s,r)=>s+r.stores,0),totalRefreshed=summaries.reduce((s,r)=>s+r.refreshed,0),totalHealthy=summaries.reduce((s,r)=>s+r.healthy,0),totalLow=summaries.reduce((s,r)=>s+r.low,0),totalOos=summaries.reduce((s,r)=>s+r.oos,0),totalUnavailable=summaries.reduce((s,r)=>s+r.unavailable,0),totalKnown=totalHealthy+totalLow+totalOos,overallRate=totalKnown>0?(totalHealthy/totalKnown)*100:null,totalCases=summaries.reduce((s,r)=>s+r.casesAdded,0),totalDollars=summaries.reduce((s,r)=>s+r.dollarsAdded,0);
 async function refreshRegion(regionKey:string){const ids=REGION_SETS[regionKey],regionStores=allStores.filter(s=>ids.has(s.id));for(let storeIndex=0;storeIndex<regionStores.length;storeIndex++){const store=regionStores[storeIndex];setRefreshProgress(`${REGION_LABELS[regionKey]}: ${storeIndex+1} / ${regionStores.length} — ${store.name}`);const rows:StoreInventorySnapshot['rows']=[];for(let i=0;i<products.length;i+=4){const batch=products.slice(i,i+4),results=await Promise.all(batch.map(async product=>{try{const q=new URLSearchParams({tcin:product.tcin,storeId:store.id}),res=await fetch(`/api/inventory?${q.toString()}`),data=await res.json();return{tcin:product.tcin,quantity:data.quantity??null,status:data.status??'UNKNOWN',availability:data.availability??'UNKNOWN'} as StoreInventorySnapshot['rows'][number]}catch{return{tcin:product.tcin,quantity:null,status:'UNKNOWN' as const,availability:'CLIENT_ERROR'}}}));rows.push(...results)}saveStoreInventorySnapshot({storeId:store.id,refreshedAt:new Date().toISOString(),rows});setSnapshots(readInventorySnapshots())}}
 async function refreshOneRegion(regionKey:string){if(refreshingKey||refreshAll)return;setRefreshingKey(regionKey);try{await refreshRegion(regionKey);setRefreshProgress(`${REGION_LABELS[regionKey]} complete`)}finally{setRefreshingKey(null)}}
 async function refreshEveryRegion(){if(refreshingKey||refreshAll)return;setRefreshAll(true);try{const keys=Object.keys(REGION_SETS);for(let i=0;i<keys.length;i++){const key=keys[i];setRefreshProgress(`Region ${i+1} / ${keys.length} — ${REGION_LABELS[key]}`);await refreshRegion(key)}setRefreshProgress('All regions complete')}finally{setRefreshAll(false)}}
 return <main id="top"><header><div><div className="eyebrow">REGIONAL PERFORMANCE VIEW</div><h1>Target Regional In-Stock Comparison</h1><p>Unavailable items are held separately and do not lower regional in-stock.</p></div><div className="headerActions"><Link className="navButton" href="/">Store Dashboard</Link><Link className="navButton" href="/unavailable">Unavailable Watch</Link><Link className="navButton" href="/orders">Case Additions Dashboard</Link><button className="primary" onClick={refreshEveryRegion} disabled={refreshAll||refreshingKey!==null}>{refreshAll?'Refreshing All Regions…':'Refresh All Regions'}</button></div></header>
 {refreshProgress&&<section className="storeCard"><div><strong>Refresh Status</strong><span>{refreshProgress}</span></div></section>}
 <section className="stats orderStats regionalStats"><div className={`stat rateCard ${overallRate===null?'neutral':overallRate>=98.5?'rateGreen':overallRate>=95?'rateYellow':'rateRed'}`}><strong>{overallRate===null?'—':`${overallRate.toFixed(1)}%`}</strong><span>All Regions In-Stock</span><small>{totalKnown>0?`${totalHealthy} / ${totalKnown} healthy`:'Refresh regions to calculate'}</small></div><div className="stat neutral"><strong>{totalRefreshed} / {totalStores}</strong><span>Stores Refreshed</span><small>{totalStores?`${((totalRefreshed/totalStores)*100).toFixed(0)}% coverage`:'0% coverage'}</small></div><div className="stat danger"><strong>{totalOos}</strong><span>Out of Stock Items</span><small>Confirmed zero quantity</small></div><div className="stat warning mobileHideRegional"><strong>{totalLow}</strong><span>Low Items (1–2)</span><small>Confirmed quantity</small></div><div className="stat neutral mobileHideRegional"><strong>{totalUnavailable}</strong><span>Unavailable Watch</span><small>Excluded from in-stock</small></div><div className="stat good mobileHideRegional"><strong>{totalCases}</strong><span>Cases Added This Week</span><small>Week of {currentWeek}</small></div><div className="stat good"><strong>{money.format(totalDollars)}</strong><span>Added $ This Week</span><small>Known case prices</small></div><button className="stat mobileRegionalRefresh" onClick={refreshEveryRegion} disabled={refreshAll||refreshingKey!==null}><strong>{refreshAll?'…':'↻'}</strong><span>{refreshAll?'Refreshing All Regions':'Refresh All Regions'}</span><small>{refreshAll?refreshProgress:'Update the total regional view'}</small></button></section>
 <section className="analysisSection"><div className="sectionTitle"><div><h2>Regional Comparison</h2><p>Lowest in-stock regions appear first. Unavailable results are separated from OOS.</p></div></div><div className="tableWrap"><table><thead><tr><th>Region</th><th>In-Stock</th><th>Stores Refreshed</th><th>Coverage</th><th>OOS</th><th>Low</th><th>Unavailable</th><th>Needs Action</th><th>Cases Added</th><th>Added $</th><th>Last Refreshed</th><th>Refresh</th></tr></thead><tbody>{summaries.map(r=><tr key={r.key}><td><strong>{r.label}</strong><br/><small>{r.stores} stores</small></td><td><span className={`pill ${rateClass(r.rate)}`}>{r.rate===null?'Not refreshed':`${r.rate.toFixed(1)}%`}</span></td><td className="qty">{r.refreshed} / {r.stores}</td><td>{r.stores?`${((r.refreshed/r.stores)*100).toFixed(0)}%`:'0%'}</td><td className="qty">{r.oos}</td><td className="qty">{r.low}</td><td className="qty">{r.unavailable}</td><td className="qty">{r.oos+r.low}</td><td className="qty">{r.casesAdded}</td><td className="moneyCell">{money.format(r.dollarsAdded)}</td><td>{r.lastRefreshed?new Date(r.lastRefreshed).toLocaleString():'—'}</td><td><button type="button" onClick={()=>refreshOneRegion(r.key)} disabled={refreshAll||refreshingKey!==null}>{refreshingKey===r.key?'Refreshing…':'Refresh'}</button></td></tr>)}</tbody></table></div></section>
 <nav className="mobileBottomNav"><Link href="/">Store</Link><a href="#top" className="active">Regions</a><Link href="/?view=attention"><span>+</span>Act</Link><Link href="/orders">Orders</Link><button onClick={refreshEveryRegion} disabled={refreshAll||refreshingKey!==null}>Refresh</button></nav>
 <footer>Unavailable items are excluded from the regional in-stock denominator and held in Unavailable Watch until Target returns a usable store quantity.</footer></main>
}
